import Head from 'next/head'
import Image from 'next/image'
import OutlineMenu from '../components/OutlineMenu'
import TabMenu from '../components/TabMenu'
import TextEditorField from '../components/TextEditorField'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>wrIDE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          wrIDE
        </div>
        <div className={styles.body}>
          <div className={styles.leftMenu}>
            <OutlineMenu color='#a7d0d8' data='test' />
          </div>
          <div className={styles.editor}>
            <TextEditorField />
          </div>
          <div className={styles.rightMenu}>
            <TabMenu color='#8ced8a' />
          </div>
        </div>
      </main>
    </div>
  )
}
